name: Typing

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  PYTHON_VERSION: 3.12
  UV_NO_SYNC: 1

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          uv venv
          uv sync
          uv pip install .[dev]
          echo "PYTHONPATH=$GITHUB_WORKSPACE/.venv/lib/python${{ env.PYTHON_VERSION }}/site-packages" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Run type checking
        run: uv run pyright src
